name: Daily Scheduled Workflow

on:
  schedule:
    - cron: '30 12 * * *' # Triggers at 6:00 PM IST daily

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "This is a scheduled task"
